package: community.lazycat.app.borg-ui
version: 2.2.6
name: Borg Web UI
description: "Borg Backup 的现代网页界面。零配置部署 - 直接运行即可。"
min_os_version: "1.5.0"
homepage: https://github.com/karanhudia/borg-ui
author: karanhudia
unsupported_platforms:
  - ios
  - android
  - tvos
locales:
  zh:
    name: Borg Web UI
    description: "Borg Backup 的现代网页界面。零配置部署 - 直接运行即可。"
  en:
    name: Borg Web UI
    description: "A modern web interface for Borg Backup. Zero-configuration deployment - just run and go."
